/// Construct the original type from its partial representation plus any fields
/// that were skipped (or otherwise not directly convertible).
///
/// `Args` is a struct containing the extra field values needed to complete the original
/// struct — typically for fields that are skipped, option-wrapped, or type-overridden.
///
/// # Example (generated by `#[partial(from_partial)]`)
///
/// ```ignore
/// #[derive(Debug, PartialEq)]
/// struct CreateUserMissing {
///     id: u64,
/// }
///
/// impl FromPartial<CreateUser> for User {
///     type Args = CreateUserMissing;
///     fn from_partial(partial: CreateUser, missing: CreateUserMissing) -> Self {
///         User { id: missing.id, name: partial.username, .. }
///     }
/// }
/// ```
pub trait FromPartial<P> {
    type Args;
    fn from_partial(partial: P, args: Self::Args) -> Self;
}

/// Convert the original type into its partial representation,
/// discarding any skipped fields.
///
/// # Example (generated by `#[partial(from_partial)]`)
///
/// ```ignore
/// impl IntoPartial<CreateUser> for User {
///     fn into_partial(self) -> CreateUser {
///         CreateUser { username: self.name, location: Some(self.location), .. }
///     }
/// }
/// ```
pub trait IntoPartial<P> {
    fn into_partial(self) -> P;
}
